export interface AvatarSeries {
  key: string
  sourceDir: string
  toneGroup: 'positive' | 'neutral_thoughtful' | 'reminder_caution' | 'negative_displeasure' | 'mockery_sarcasm' | 'surprise_fear'
  stage: 1
  layers: 1 | 2 | 3 | 4 | 5 | 6
  description: string
  intensity: string
}

const fullSeries: AvatarSeries[] = [
  // ── positive (13) ──
  {
    key: 'affirmation',
    sourceDir: 'affirmation',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Спокойное подтверждение, согласие, одобрение',
    intensity: 'Низкая — мягкое утверждение',
  },
  {
    key: 'important_affirmation',
    sourceDir: 'important_affirmation',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Важное, весомое подтверждение / подчёркнутое одобрение',
    intensity: 'Средняя — уверенное утверждение',
  },
  {
    key: 'joy',
    sourceDir: 'joy',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Чистая радость, позитивная реакция',
    intensity: 'Высокая — открытая радость',
  },
  {
    key: 'joy_and_admiration',
    sourceDir: 'joy_and_admiration',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Радость с восхищением, восторженное одобрение',
    intensity: 'Высокая — восторженность',
  },
  {
    key: 'joy_and_support',
    sourceDir: 'joy_and_support',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Радость с поддержкой, тёплое поощрение',
    intensity: 'Высокая — радостная поддержка',
  },
  {
    key: 'joy_user_success',
    sourceDir: 'joy_user_success',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Радость за успех пользователя, гордость',
    intensity: 'Высокая — восторг за достижение',
  },
  {
    key: 'laughter_1',
    sourceDir: 'laughter_1',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Смех, весёлая реакция (вар. 1)',
    intensity: 'Высокая — звонкий смех',
  },
  {
    key: 'laughter_2',
    sourceDir: 'laughter_2',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Смех, весёлая реакция (вар. 2)',
    intensity: 'Высокая — заразительный смех',
  },
  {
    key: 'laughter_and_joy_v1',
    sourceDir: 'laughter_and_joy_v1',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Смех и радость, бурное веселье',
    intensity: 'Высокая — безудержное веселье',
  },
  {
    key: 'cheerful_approval',
    sourceDir: 'cheerful_approval',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Бодрое одобрение, жизнерадостное согласие',
    intensity: 'Средняя — энергичное одобрение',
  },
  {
    key: 'success',
    sourceDir: 'success',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Успех, достижение, победа',
    intensity: 'Высокая — триумф',
  },
  {
    key: 'satisfaction',
    sourceDir: 'satisfaction',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Удовлетворение, спокойная радость от результата',
    intensity: 'Средняя — contentment',
  },
  {
    key: 'satisfaction_user_action',
    sourceDir: 'satisfaction_user_action',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Удовлетворение действием пользователя, одобрение поступка',
    intensity: 'Средняя — удовлетворение',
  },

  // ── neutral_thoughtful (16) ──
  {
    key: 'thoughtful',
    sourceDir: 'thoughtful',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Задумчивость, размышление, пауза',
    intensity: 'Низкая — спокойное размышление',
  },
  {
    key: 'thoughtful_v1',
    sourceDir: 'thoughtful_v1',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Задумчивость (альтернативный вариант)',
    intensity: 'Низкая — мягкая задумчивость',
  },
  {
    key: 'explanation',
    sourceDir: 'explanation',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Объяснение, нейтральное разъяснение',
    intensity: 'Низкая — спокойное пояснение',
  },
  {
    key: 'clear_explanation',
    sourceDir: 'clear_explanation',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Чёткое, структурированное объяснение',
    intensity: 'Средняя — уверенное разъяснение',
  },
  {
    key: 'understanding_nuances',
    sourceDir: 'understanding_nuances',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Понимание нюансов, вдумчивость',
    intensity: 'Низкая — тонкое понимание',
  },
  {
    key: 'subtleties',
    sourceDir: 'subtleties',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Тонкости, деликатный намёк, полутона',
    intensity: 'Низкая — нюанс',
  },
  {
    key: 'curiosity',
    sourceDir: 'curiosity',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Любопытство, интерес',
    intensity: 'Средняя — заинтересованность',
  },
  {
    key: 'curious_surprise',
    sourceDir: 'curious_surprise',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Любопытное удивление, заинтересованное изумление',
    intensity: 'Средняя — удивлённый интерес',
  },
  {
    key: 'wondering_thought',
    sourceDir: 'wondering_thought',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Задумчивое удивление, размышление вслух',
    intensity: 'Средняя — удивлённое раздумье',
  },
  {
    key: 'thought_and_surprise',
    sourceDir: 'thought_and_surprise',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Мысль с оттенком удивления, неожиданное осознание',
    intensity: 'Средняя — неожиданная мысль',
  },
  {
    key: 'questioning',
    sourceDir: 'questioning',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Вопрос, недоумение, запрос информации',
    intensity: 'Низкая — вопросительная',
  },
  {
    key: 'questioning_surprise_user_action',
    sourceDir: 'questioning_surprise_user_action',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Вопросительное удивление действием пользователя',
    intensity: 'Средняя — озадаченность',
  },
  {
    key: 'admiration',
    sourceDir: 'admiration',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Восхищение, уважение, признание',
    intensity: 'Средняя — тёплое восхищение',
  },
  {
    key: 'scrutinizing',
    sourceDir: 'scrutinizing',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Внимательное изучение, пристальный взгляд',
    intensity: 'Средняя — пристальное внимание',
  },
  {
    key: 'dreams_and_fantasies',
    sourceDir: 'dreams_and_fantasies',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Мечты и фантазии, отстранённая задумчивость',
    intensity: 'Низкая — мечтательность',
  },
  {
    key: 'fantasizing',
    sourceDir: 'fantasizing',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Фантазирование, погружение в воображение',
    intensity: 'Средняя — активное воображение',
  },

  // ── reminder_caution (9) ──
  {
    key: 'useful_reminder',
    sourceDir: 'useful_reminder',
    toneGroup: 'reminder_caution',
    stage: 1,
    layers: 6,
    description: 'Полезное напоминание, дружеский совет',
    intensity: 'Низкая — мягкое напоминание',
  },
  {
    key: 'important_reminder',
    sourceDir: 'important_reminder',
    toneGroup: 'reminder_caution',
    stage: 1,
    layers: 6,
    description: 'Важное напоминание, серьёзное предупреждение',
    intensity: 'Средняя — серьёзное напоминание',
  },
  {
    key: 'cheerful_reminder',
    sourceDir: 'cheerful_reminder',
    toneGroup: 'reminder_caution',
    stage: 1,
    layers: 6,
    description: 'Бодрое напоминание, подбадривающее предупреждение',
    intensity: 'Средняя — жизнерадостное напоминание',
  },
  {
    key: 'important_warning',
    sourceDir: 'important_warning',
    toneGroup: 'reminder_caution',
    stage: 1,
    layers: 6,
    description: 'Критическое предупреждение, строгий сигнал',
    intensity: 'Высокая — максимальная серьёзность',
  },
  {
    key: 'serious_reminder_warning',
    sourceDir: 'serious_reminder_warning',
    toneGroup: 'reminder_caution',
    stage: 1,
    layers: 6,
    description: 'Серьёзное напоминание-предупреждение',
    intensity: 'Высокая — строгое предупреждение',
  },
  {
    key: 'warning',
    sourceDir: 'warning',
    toneGroup: 'reminder_caution',
    stage: 1,
    layers: 6,
    description: 'Предупреждение, сигнал о риске',
    intensity: 'Высокая — серьёзное предупреждение',
  },
  {
    key: 'warning_and_prohibition',
    sourceDir: 'warning_and_prohibition',
    toneGroup: 'reminder_caution',
    stage: 1,
    layers: 6,
    description: 'Предупреждение с запретом, строгое ограничение',
    intensity: 'Высокая — категоричное предупреждение',
  },
  {
    key: 'caution',
    sourceDir: 'caution',
    toneGroup: 'reminder_caution',
    stage: 1,
    layers: 6,
    description: 'Осторожность, аккуратность, предостережение',
    intensity: 'Средняя — настороженность',
  },
  {
    key: 'important_clarification',
    sourceDir: 'important_clarification',
    toneGroup: 'reminder_caution',
    stage: 1,
    layers: 6,
    description: 'Важное уточнение, принципиальное разъяснение',
    intensity: 'Средняя — существенное пояснение',
  },

  // ── negative_displeasure (12) ──
  {
    key: 'annoyed',
    sourceDir: 'annoyed',
    toneGroup: 'negative_displeasure',
    stage: 1,
    layers: 6,
    description: 'Лёгкое раздражение, досада',
    intensity: 'Низкая — лёгкая досада',
  },
  {
    key: 'disappointment',
    sourceDir: 'disappointment',
    toneGroup: 'negative_displeasure',
    stage: 1,
    layers: 6,
    description: 'Разочарование, неоправдавшиеся ожидания',
    intensity: 'Средняя — разочарование',
  },
  {
    key: 'disappointment_and_dissatisfaction',
    sourceDir: 'disappointment_and_dissatisfaction',
    toneGroup: 'negative_displeasure',
    stage: 1,
    layers: 6,
    description: 'Разочарование с недовольством, глубокое неудовлетворение',
    intensity: 'Высокая — сильное разочарование',
  },
  {
    key: 'denial',
    sourceDir: 'denial',
    toneGroup: 'negative_displeasure',
    stage: 1,
    layers: 6,
    description: 'Отрицание, несогласие, отказ',
    intensity: 'Средняя — твёрдое отрицание',
  },
  {
    key: 'denial_and_prohibitions',
    sourceDir: 'denial_and_prohibitions',
    toneGroup: 'negative_displeasure',
    stage: 1,
    layers: 6,
    description: 'Отрицание с запретом, категорический отказ',
    intensity: 'Высокая — жёсткий отказ',
  },
  {
    key: 'rejection_denial_fatigue',
    sourceDir: 'rejection_denial_fatigue',
    toneGroup: 'negative_displeasure',
    stage: 1,
    layers: 6,
    description: 'Отторжение с усталостью, утомлённый отказ',
    intensity: 'Средняя — усталое неприятие',
  },
  {
    key: 'offense',
    sourceDir: 'offense',
    toneGroup: 'negative_displeasure',
    stage: 1,
    layers: 6,
    description: 'Обида, чувство несправедливости',
    intensity: 'Средняя — обида',
  },
  {
    key: 'offense_and_anger',
    sourceDir: 'offense_and_anger',
    toneGroup: 'negative_displeasure',
    stage: 1,
    layers: 6,
    description: 'Обида с гневом, возмущение',
    intensity: 'Высокая — гневная обида',
  },
  {
    key: 'irritation_and_anger',
    sourceDir: 'irritation_and_anger',
    toneGroup: 'negative_displeasure',
    stage: 1,
    layers: 6,
    description: 'Раздражение и гнев, нарастающее негодование',
    intensity: 'Высокая — сильное раздражение',
  },
  {
    key: 'anger',
    sourceDir: 'anger',
    toneGroup: 'negative_displeasure',
    stage: 1,
    layers: 6,
    description: 'Гнев, ярость, сильное негодование',
    intensity: 'Высокая — ярость',
  },
  {
    key: 'screaming',
    sourceDir: 'screaming',
    toneGroup: 'negative_displeasure',
    stage: 1,
    layers: 6,
    description: 'Крик, эмоциональный всплеск',
    intensity: 'Высокая — крик',
  },
  {
    key: 'anna_screaming',
    sourceDir: 'anna_screaming',
    toneGroup: 'negative_displeasure',
    stage: 1,
    layers: 6,
    description: 'Анна кричит, крайняя степень эмоций',
    intensity: 'Высокая — истерический крик',
  },

  // ── mockery_sarcasm (7) ──
  {
    key: 'mockery',
    sourceDir: 'mockery',
    toneGroup: 'mockery_sarcasm',
    stage: 1,
    layers: 6,
    description: 'Насмешка, ирония, подтрунивание',
    intensity: 'Средняя — насмешка',
  },
  {
    key: 'mockery_interlocutor',
    sourceDir: 'mockery_interlocutor',
    toneGroup: 'mockery_sarcasm',
    stage: 1,
    layers: 6,
    description: 'Насмешка над собеседником, колкость',
    intensity: 'Средняя — колкая насмешка',
  },
  {
    key: 'condescension',
    sourceDir: 'condescension',
    toneGroup: 'mockery_sarcasm',
    stage: 1,
    layers: 6,
    description: 'Снисходительность, покровительственный тон',
    intensity: 'Низкая — снисхождение',
  },
  {
    key: 'flirting',
    sourceDir: 'flirting',
    toneGroup: 'mockery_sarcasm',
    stage: 1,
    layers: 6,
    description: 'Флирт, игривость, кокетство',
    intensity: 'Средняя — игривость',
  },
  {
    key: 'flirting_and_teasing',
    sourceDir: 'flirting_and_teasing',
    toneGroup: 'mockery_sarcasm',
    stage: 1,
    layers: 6,
    description: 'Флирт с поддразниванием, шаловливость',
    intensity: 'Средняя — шаловливый флирт',
  },
  {
    key: 'sweet_sour',
    sourceDir: 'sweet_sour',
    toneGroup: 'mockery_sarcasm',
    stage: 1,
    layers: 6,
    description: 'Кисло-сладкая реакция, двусмысленная улыбка',
    intensity: 'Средняя — двусмысленность',
  },
  {
    key: 'sweet_to_sour',
    sourceDir: 'sweet_to_sour',
    toneGroup: 'mockery_sarcasm',
    stage: 1,
    layers: 6,
    description: 'От сладкого к кислому, смена настроения',
    intensity: 'Средняя — переменчивость',
  },

  // ── surprise_fear (6) ──
  {
    key: 'surprise',
    sourceDir: 'surprise',
    toneGroup: 'surprise_fear',
    stage: 1,
    layers: 6,
    description: 'Удивление, неожиданность',
    intensity: 'Средняя — удивление',
  },
  {
    key: 'frightened_surprise',
    sourceDir: 'frightened_surprise',
    toneGroup: 'surprise_fear',
    stage: 1,
    layers: 6,
    description: 'Испуганное удивление, переполох',
    intensity: 'Высокая — испуг',
  },
  {
    key: 'curiosity_and_surprise',
    sourceDir: 'curiosity_and_surprise',
    toneGroup: 'surprise_fear',
    stage: 1,
    layers: 6,
    description: 'Любопытство с оттенком удивления',
    intensity: 'Средняя — заинтригованность',
  },
  {
    key: 'sick',
    sourceDir: 'sick',
    toneGroup: 'surprise_fear',
    stage: 1,
    layers: 6,
    description: 'Болезненное состояние, нездоровье, слабость',
    intensity: 'Низкая — болезненность',
  },
  {
    key: 'anna_secrets',
    sourceDir: 'anna_secrets',
    toneGroup: 'surprise_fear',
    stage: 1,
    layers: 6,
    description: 'Таинственность, секреты, загадочность',
    intensity: 'Низкая — загадочность',
  },
  {
    key: 'misunderstanding',
    sourceDir: 'misunderstanding',
    toneGroup: 'surprise_fear',
    stage: 1,
    layers: 6,
    description: 'Непонимание, растерянность, замешательство',
    intensity: 'Средняя — недоумение',
  },
]

export const avatarManifest = {
  version: '2.0.0',
  stage: 1,
  totalSeries: fullSeries.length,
  sourceBase: '../anna',
  description: 'Полный набор из 63 эмоций Анны для v7.5',
  groups: {
    positive: fullSeries.filter((s) => s.toneGroup === 'positive'),
    neutral_thoughtful: fullSeries.filter((s) => s.toneGroup === 'neutral_thoughtful'),
    reminder_caution: fullSeries.filter((s) => s.toneGroup === 'reminder_caution'),
    negative_displeasure: fullSeries.filter((s) => s.toneGroup === 'negative_displeasure'),
    mockery_sarcasm: fullSeries.filter((s) => s.toneGroup === 'mockery_sarcasm'),
    surprise_fear: fullSeries.filter((s) => s.toneGroup === 'surprise_fear'),
  },
  series: fullSeries.reduce(
    (acc, s) => {
      acc[s.key] = s
      return acc
    },
    {} as Record<string, AvatarSeries>,
  ),
}
