export interface AvatarSeries {
  key: string
  sourceDir: string
  toneGroup: 'positive' | 'neutral_thoughtful' | 'reminder_caution'
  stage: 1
  layers: 1 | 2 | 3 | 4 | 5 | 6
  description: string
  intensity: string
}

export const curatedSeries: AvatarSeries[] = [
  {
    key: 'affirmation',
    sourceDir: 'affirmation',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Спокойное подтверждение, согласие, одобрение',
    intensity: 'Низкая — мягкое утверждение',
  },
  {
    key: 'important_affirmation',
    sourceDir: 'important_affirmation',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Важное, весомое подтверждение / подчёркнутое одобрение',
    intensity: 'Средняя — уверенное утверждение',
  },
  {
    key: 'joy',
    sourceDir: 'joy',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Чистая радость, позитивная реакция',
    intensity: 'Высокая — открытая радость',
  },
  {
    key: 'joy_and_support',
    sourceDir: 'joy_and_support',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Радость с поддержкой, тёплое поощрение',
    intensity: 'Высокая — радостная поддержка',
  },
  {
    key: 'joy_user_success',
    sourceDir: 'joy_user_success',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Радость за успех пользователя, гордость',
    intensity: 'Высокая — восторг за достижение',
  },
  {
    key: 'success',
    sourceDir: 'success',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Успех, достижение, победа',
    intensity: 'Высокая — триумф',
  },
  {
    key: 'satisfaction',
    sourceDir: 'satisfaction',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Удовлетворение, спокойная радость от результата',
    intensity: 'Средняя — contentment',
  },
  {
    key: 'cheerful_approval',
    sourceDir: 'cheerful_approval',
    toneGroup: 'positive',
    stage: 1,
    layers: 6,
    description: 'Бодрое одобрение, жизнерадостное согласие',
    intensity: 'Средняя — энергичное одобрение',
  },
  {
    key: 'thoughtful',
    sourceDir: 'thoughtful',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Задумчивость, размышление, пауза',
    intensity: 'Низкая — спокойное размышление',
  },
  {
    key: 'thoughtful_v1',
    sourceDir: 'thoughtful_v1',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Задумчивость (альтернативный вариант)',
    intensity: 'Низкая — мягкая задумчивость',
  },
  {
    key: 'explanation',
    sourceDir: 'explanation',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Объяснение, нейтральное разъяснение',
    intensity: 'Низкая — спокойное пояснение',
  },
  {
    key: 'clear_explanation',
    sourceDir: 'clear_explanation',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Чёткое, структурированное объяснение',
    intensity: 'Средняя — уверенное разъяснение',
  },
  {
    key: 'understanding_nuances',
    sourceDir: 'understanding_nuances',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Понимание нюансов, вдумчивость',
    intensity: 'Низкая — тонкое понимание',
  },
  {
    key: 'subtleties',
    sourceDir: 'subtleties',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Тонкости, деликатный намёк, полутона',
    intensity: 'Низкая — нюанс',
  },
  {
    key: 'questioning',
    sourceDir: 'questioning',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Вопрос, недоумение, запрос информации',
    intensity: 'Низкая — вопросительная',
  },
  {
    key: 'curiosity',
    sourceDir: 'curiosity',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Любопытство, интерес',
    intensity: 'Средняя — заинтересованность',
  },
  {
    key: 'curious_surprise',
    sourceDir: 'curious_surprise',
    toneGroup: 'neutral_thoughtful',
    stage: 1,
    layers: 6,
    description: 'Любопытное удивление, заинтересованное изумление',
    intensity: 'Средняя — удивлённый интерес',
  },
  {
    key: 'useful_reminder',
    sourceDir: 'useful_reminder',
    toneGroup: 'reminder_caution',
    stage: 1,
    layers: 6,
    description: 'Полезное напоминание, дружеский совет',
    intensity: 'Низкая — мягкое напоминание',
  },
  {
    key: 'important_reminder',
    sourceDir: 'important_reminder',
    toneGroup: 'reminder_caution',
    stage: 1,
    layers: 6,
    description: 'Важное напоминание, серьёзное предупреждение',
    intensity: 'Средняя — серьёзное напоминание',
  },
  {
    key: 'cheerful_reminder',
    sourceDir: 'cheerful_reminder',
    toneGroup: 'reminder_caution',
    stage: 1,
    layers: 6,
    description: 'Бодрое напоминание, подбадривающее предупреждение',
    intensity: 'Средняя — жизнерадостное напоминание',
  },
  {
    key: 'caution',
    sourceDir: 'caution',
    toneGroup: 'reminder_caution',
    stage: 1,
    layers: 6,
    description: 'Осторожность, аккуратность, предостережение',
    intensity: 'Средняя — настороженность',
  },
  {
    key: 'warning',
    sourceDir: 'warning',
    toneGroup: 'reminder_caution',
    stage: 1,
    layers: 6,
    description: 'Предупреждение, сигнал о риске',
    intensity: 'Высокая — серьёзное предупреждение',
  },
  {
    key: 'important_warning',
    sourceDir: 'important_warning',
    toneGroup: 'reminder_caution',
    stage: 1,
    layers: 6,
    description: 'Критическое предупреждение, строгий сигнал',
    intensity: 'Высокая — максимальная серьёзность',
  },
  {
    key: 'important_clarification',
    sourceDir: 'important_clarification',
    toneGroup: 'reminder_caution',
    stage: 1,
    layers: 6,
    description: 'Важное уточнение, принципиальное разъяснение',
    intensity: 'Средняя — существенное пояснение',
  },
]

export const avatarManifest = {
  version: '1.0.0',
  stage: 1,
  totalSeries: curatedSeries.length,
  sourceBase: '../anna',
  description: 'Curated safe-set of Anna avatars for phase 1',
  groups: {
    positive: curatedSeries.filter((s) => s.toneGroup === 'positive'),
    neutral_thoughtful: curatedSeries.filter((s) => s.toneGroup === 'neutral_thoughtful'),
    reminder_caution: curatedSeries.filter((s) => s.toneGroup === 'reminder_caution'),
  },
  series: curatedSeries.reduce(
    (acc, s) => {
      acc[s.key] = s
      return acc
    },
    {} as Record<string, AvatarSeries>,
  ),
}
